io.write("SYSTEM GOING TO HALT NOW!")
local component = require("component")
os.sleep(10)
io.write("syserror")
local computer = require("computer")
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.beep()
computer.getDeviceInfo()
os.sleep(3)
computer.shutdown()
