-- Интепретатор html by Laine_prikol
local args = {...}
i = math.random(0,1000000)
s = 'wget '..args[1]..' /tmp/'..i
os.execute(s)
os.sleep(1)
i = tostring(i)
local filehtml = io.open("/tmp/"..i, "r")
a = filehtml:read("*a")
a = string.gsub(a, "<p>", "")
a = string.gsub(a, "</p>", "")
a = string.gsub(a, "<h1>", "")
a = string.gsub(a, "</h1>", "")
a = string.gsub(a, "<h2>", "")
a = string.gsub(a, "</h2>", "")
a = string.gsub(a, "<strong>", "")
a = string.gsub(a, "</strong>", "")
a = string.gsub(a, "<strong>", "")
a = string.gsub(a, "</strong>", "")
a = string.gsub(a, "<a>", "")
a = string.gsub(a, "</a>", "")
a = string.gsub(a, "<!DOCTYPE html>", "")
a = string.gsub(a, "!doctype html", "")
a = string.gsub(a, "<html><head>", "")
a = string.gsub(a, "</body></html>", "")
a = string.gsub(a, "<body>", "")
a = string.gsub(a, "<a href=", " ")
a = string.gsub(a, ">", "")
a = string.gsub(a, "<", "")
a = string.gsub(a, "class=", "")
a = string.gsub(a, "footer", "")
a = string.gsub(a, "<meta charset=", "")
a = string.gsub(a, "utf-8", "")
a = string.gsub(a, "meta", "")
a = string.gsub(a, "name", "")
a = string.gsub(a, "content=", "")
a = string.gsub(a, "text/html", "")
a = string.gsub(a, "text/css", "")
a = string.gsub(a, "rel=", " ")
a = string.gsub(a, "stylesheet", "")
a = string.gsub(a, ".css", "")
a = string.gsub(a, "/head", "")
a = string.gsub(a, "/body", "")
a = string.gsub(a, "/html", "")
a = string.gsub(a, "type=", "")
a = string.gsub(a, "<title>", "")
a = string.gsub(a, "</title>", "")
a = string.gsub(a, "link", "")
a = string.gsub(a, "=", "")
a = string.gsub(a, ";", "")
a = string.gsub(a, "/code", "")
a = string.gsub(a, "utf-8", "")
a = string.gsub(a, "viewport", "")
a = string.gsub(a, "content-type", "")
a = string.gsub(a, "title", "")
a = string.gsub(a, "charsetUTF-8", "")
a = string.gsub(a, "charset", "")
a = string.gsub(a, "href", "")
a = string.gsub(a, "http-equiv", "")
a = string.gsub(a, "icon", "")
a = string.gsub(a, "image", "")
a = string.gsub(a, "favicon", "")
a = string.gsub(a, ".png", "")
a = string.gsub(a, '"', "")
a = string.gsub(a, ".ico", "")
a = string.gsub(a, "head", "")
filehtml:close()
local fileconverted = io.open("/webpage"..i, "w")
fileconverted = fileconverted:write(a)
fileconverted:close()
os.execute("view webpage"..i)
os.execute("rm webpage"..i)
print("viewing complete!")